### ISSUE TITLE
Possible to use variables from YAML block within the Markdown document?

### ISSUE THREAD

**Issue by commadelimited** [Flask-FlatPages/Flask-FlatPages#51]
I'd like to define a variable within the YAML block at the top of my markdown pages that can be used in other areas of the site, AND within the document itself. In my specific case I'd like to store an Amazon affiliate URL, but don't want to duplicate the value.

Currently when outputting page information I can get the meta of a page:

```
page.meta.get('affiliate_url')
```

But I can't seem to use that variable within the document itself. Is this possible?

**Comment by commadelimited** [comment]
Bump.

**Comment by padraic-padraic** [comment]
One option (though I've not tested) would be to put the variable in jinja syntax like
`[this is the linl]({{page.affiliate_url}})`
in the markdown body. When the template is rendered jinja could then access the meta variable?
