### ISSUE TITLE
Absolute paths in FLATPAGES_ROOT are ignored

### ISSUE THREAD

**Issue by ckuhl** [Flask-FlatPages/Flask-FlatPages#61]
If I try to configure my flatpages root from an absolute path, it munges it. Given the following line:
    FLATPAGES_BLOG_ROOT = os.path.join(settings.BASE_DIR, 'content', 'blog')

The expected path is:
    /home/ckuhl/dev/ckuhl.com/content/blog

And the actual path is:
    /home/ckuhl/dev/ckuhl.com/ckuhl/pages

I have written a patch for it, and created a pull request (pull request #60).

**Comment by padraic-padraic** [comment]
As discussed on pull request #60, absolute paths are already supported. Your bug is likely to do with the flatpages name.
