### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by playpauseandstop** [Flask-FlatPages/Flask-FlatPages#67]
Hi.

As you might noticed this repo, not very well maintained over last year or so. Mainly because of personal reasons.

But today I saw the great pull request #66, so decided to work a bit this project release version 1.0 and try to find new maintainer for the repo.

If you're interested in maintaining the repo, feel free to contact me at iam@igordavydenko.com. If you know the collective initiatives like jazzband, but in Flask ecosystem - let me know.

In any case, I'm open on your suggestions and willing to find new maintainer for the extension, that badly maintained recently.

Thanks, Igor

**Comment by playpauseandstop** [comment]
Hi @SimonSapin,

As wrote above I'm unable to continue maintaining `Flask-FlatPages` repo, but unfortunately I haven't any rights to make @padraic-padraic or anyone else as a new maintainer. 

With that in mind can you provide necessary rights to @padraic-padraic and remove maintainer rights from me?

Thanks, Igor

**Comment by SimonSapin** [comment]
Done.

**Comment by playpauseandstop** [comment]
@SimonSapin thanks!

**Everyone:** please welcome @padraic-padraic as new `Flask-FlatPages` maintainer! Woohoo!
