### ISSUE TITLE
markdown 3.0 changed its function signature

### ISSUE THREAD

**Issue by jmonteironet** [Flask-FlatPages/Flask-FlatPages#69]
Hello, I was updating my requirements on a project when I stumbled upon this.

Python-Markdown 3.0 removed the positional arguments (Python-Markdown/markdown@fd628f3e540425b883f36a9c0d288ef1aafdb19e) and it broke. The deprecation seems to be from version 2.5, so maybe just require 2.5+ and fix the issue.

Thank you =)

**Comment by padraic-padraic** [comment]
I've had the same issue, I'll be pushing a new release soon upgrading to Flask 1.0 and pinning Markdown <3.0

**Comment by padraic-padraic** [comment]
v0.6.1 is now live on PyPI!
