### ISSUE TITLE
Flask-FlatPages with Blueprint

### ISSUE THREAD

**Issue by hkyq** [Flask-FlatPages/Flask-FlatPages#71]
Hey, does anyone know how I could use Flask-FlatPages with a flask blueprint? I have this code:

```
from flask_flatpages import FlatPages
from flask import Blueprint, current_app

blog_bp = Blueprint("blog", __name__)
pages = FlatPages(blog_bp)

@blog_bp.route('/<path:path>/')
def page(path):
    return pages.get_or_404(path).html
```
I'm getting `AttributeError: 'Blueprint' object has no attribute 'config'`. I also tried using `current_app`, but I got a similar error. Has anyone tried doing this?

**Comment by jmonteironet** [comment]
The way I've done is by instantiating the plugin with the main app and importing it on the blueprint.

Heres a [gist](https://gist.github.com/jmonteironet/29a435b42e9532153b1d728762b8a75f) to help.

**Comment by amandamcg** [comment]
The gist mentioned above is now 404'ing, so not sure if it also held the solution to this. I'm documenting how I got it to work for a "blog" blueprint, in case anyone else hits this issue.

Steps:
1. add FlatPages as an extension
```
from flask_flatpages import FlatPages
pages = FlatPages()
```
1. init flatpages with the correct version of app
- in __init__.py in the base module, import FlatPages `from .extensions import pages`
- then init it by calling `pages.init_app(app)`

1. update FLATPAGES_ROOT to go to look in the blueprint / module: 
- `FLATPAGES_ROOT = '../blueprints/blog/posts'`

From there, all the flatpages documentation seems to work even using blueprints.
