### ISSUE TITLE
HTML not render

### ISSUE THREAD

**Issue by mikeyakymenko** [Flask-FlatPages/Flask-FlatPages#73]
0.7.1 Version HTML render doesn't work. {{ page }} or {{ page.html|safe }}... returns nothing. Also 0.7.0 the same problem.

Got an error:

```
AttributeError: 'module' object has no attribute 'codehilite'
```

I'm wondering, but even doesn't use this extension.

**Comment by padraic-padraic** [comment]
Thank you for catching this! These lines are not run in the test suite currently, and which I will remedy. Will push a fix now.
