### ISSUE TITLE
inspect.getargspec() is deprecated

### ISSUE THREAD

**Issue by zgoda** [Flask-FlatPages/Flask-FlatPages#77]
Running tests against Python 3.8 yields a warning:

DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()

https://github.com/Flask-FlatPages/Flask-FlatPages/blob/master/flask_flatpages/flatpages.py#L307

**Comment by jlusiardi** [comment]
I ran into this warning as well and propose a solution in my PR.
