### ISSUE TITLE
Mislabeled FLATPAGES_EXTENSION_CONFIG in Docs

### ISSUE THREAD

**Issue by joshbduncan** [Flask-FlatPages/Flask-FlatPages#79]
While trying to enable an extension using the updated format and I noticed your documentation listed both "FLATPAGES_EXTENSION_CONFIG" and "FLATPAGES_EXTENSION_CONFIGS" with an "S". This was a bit confusing so I just copied the sample code from your documentation like below but it wasn't working.

```
FLATPAGES_EXTENSION_CONFIG = {
    'codehilite': {
        'linenums': 'True'
    }
}
```

Seems the variable should include the "S" like this...
```
FLATPAGES_EXTENSION_CONFIGS = {
    'codehilite': {
        'linenums': 'True'
    }
}
```

Thought this may help someone else from going down a rabbit hole like I did.

Thanks for your great work! 👍

**Comment by padraic-padraic** [comment]
Great catch, thanks for that. Will patch the docs!
