### ISSUE TITLE
File name is not shown in ReaderError

### ISSUE THREAD

**Issue by arifulhaqueHO** [Flask-FlatPages/Flask-FlatPages#85]
Our team is using FlatPages to read markdown pages. However due to special unicode FlatPages was unable to read certain markdown files.
The error we received was 
`yaml.reader.ReaderError: unacceptable character #x000b: special characters are not allowed
  in "<file>", position 1336`

As you can see from the error there is temp file name `<file>`. This caused problem as we had 100s of markdown files and it was quite hard to find the file. Luckily we had only one file broken so binary search was enough to find it. However, in the case it was more then one it would be much harder to find.

This error was found when upgrading FlatPages from 0.7.3 to 0.8.1. From my understanding the major change was a new parser.

I had look at the FlatPage and pyYaml code and have found that at [this line](https://github.com/Flask-FlatPages/Flask-FlatPages/blob/14579019ce975f7b164357e9e64b12b5419d1375/flask_flatpages/flatpages.py#L292) you are using pyYaml's safeLoader. You are passing the StringIO of the markdown content. The StringIO doesn't include name as a attribute. From pyYaml's safeloader class it is initialising a [reader class](https://github.com/yaml/pyyaml/blob/957ae4d495cf8fcb5475c6c2f1bce801096b68a5/lib/yaml/loader.py#L34C21-L34C21). 
This reader class is setting the name as None. It then [sets name attribute](https://github.com/yaml/pyyaml/blob/957ae4d495cf8fcb5475c6c2f1bce801096b68a5/lib/yaml/reader.py#L82C13-L82C13) to the stream's (the stringio content) name attribute. Defaulting to `<file>` if it doent have one. Since our stringio class will never have one it will always default to `<file>`.

I would like to suggest to include the name somehow in the stream for the safeloader class so we can have easier time to debug broken files.
Since the stream can be anything it might be useful to have StringIO wrapper class that will have the filename attribute.
I saw [this issue](https://github.com/python/typeshed/issues/1790)
Modifying some code from that I was able to create this 
```python
from yaml import SafeLoader

from io import StringIO


class NamedStringIO(StringIO):
    def __init__(self, content: str, name: str) -> None:
        super().__init__(content)
        self.name = name


nsio = NamedStringIO("Hello World ", "hello.txt as example")

print(nsio.name)

yaml_loader = SafeLoader(nsio)

print(yaml_loader)
```

It gave the error 
`yaml.reader.ReaderError: unacceptable character #x000b: special characters are not allowed
  in "hello.txt as example", position 12 `

Please let me know if you have any other questions!

**Comment by padraic-padraic** [comment]
Thank you for the very detailed suggestion, I'll implement this happily.
